// contextos/temas/Temas.js
export const temas = {
  claro: {
    background: '#F5F5F5',
    texto: '#333333',
    link: '#1E90FF',
    card: '#FFFFFF',
    noticiaBackground: '#F0F0F0',
    botao: '#1E90FF',
    borda: '#CCCCCC',
    erro: '#FF6347',
    sombra: '#000000',
    placeholder: '#CCCCCC',
    fonteTitulo: 'Montserrat-Bold',
    fonteTexto: 'Montserrat-Regular',
  },
  escuro: {
    background: '#121212',
    texto: '#FFFFFF',
    link: '#BB86FC',
    card: '#1E1E1E',
    noticiaBackground: '#2C2C2C',
    botao: '#BB86FC',
    borda: '#333333',
    erro: '#FF6B6B',
    sombra: '#FFFFFF',
    placeholder: '#555555',
    fonteTitulo: 'Montserrat-Bold',
    fonteTexto: 'Montserrat-Regular',
  },
};
